export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const RESET_USER_INFO = 'RESET_USER_INFO';

export const SET_ALL_QUESTIONNAIRE = 'SET_ALL_QUESTIONNAIRE';
export const ADD_QUESTIONNAIRE = 'ADD_QUESTIONNAIRE';
export const REMOVE_QUESTIONNAIRE = 'REMOVE_QUESTIONNAIRE';
export const UPDATE_QUESTIONNAIRE = 'UPDATE_QUESTIONNAIRE';

export const ADD_QUIZ = 'ADD_QUIZ'